# Generated by Django 3.2.15 on 2022-08-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
