# Generated by Django 3.0 on 2022-08-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220823_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
